### ISSUE TITLE
InPlaceResourceOptimization Rewirteing CSS problem

### ISSUE THREAD

**Issue by Jurigag** [apache/incubator-pagespeed-mod#1102]
I have some kind of problem. People are reporting me that page sometimes loads without styles when it should be with.

Also im using apache2 + mod_pagespeed and nginx as proxy but static files are served by apache2(im using plesk panel so i cant compile nginx + pagespeed beacause plesk use their own)

Also i have multiple domains, maybe i have to configure them somehow special ?

My config:

http://pastebin.com/BSxB60z4 - prioritze critical css is disabled
how it sometimes looks like : http://imageshack.com/a/img673/6971/tWacV8.jpg
how it supposed to look : http://imageshack.com/a/img538/9783/6b83an.png

**Comment by crowell** [comment]
can you check with the chrome/firefox page inspector (f12) to see if some files are not getting loaded and what errors there are? Is it only happening on that admin page, or is it happening in another public place on the site where it would be possible to reproduce.

**Comment by Jurigag** [comment]
It just error 404 - it happens when it try first time to parse css, its pretty hard to reproduce beacause its totally random :/

Sometimes there are error 404, sometimes not, can it happening beacause of memcached ?

tried on/off - happens same randomly times

**Comment by Jurigag** [comment]
Oh sorry, its not 404 -  its just fail with no any response. So my guess sometimes its just failing something. Are there are any logo for pagespeed.

**Comment by Jurigag** [comment]
Okay - it looks like pagespeed InPlaceResourceOptimization on; causing a problem, when i commented it it works fine.

But also without it it doesnt rewirte css, i dont know whats going on, testing on two servers with diffrent system on newest nginx and pagespeed

I can reproduce it if you want but you have to write me - beacause i have to flush cache before you check it

**Comment by jeffkaufman** [comment]
Could you try this again with our new release, 1.9.32.6?  We've a couple bugs that could have caused situations like this.

**Comment by Jurigag** [comment]
Well i installed it and still there are some bugs but i THINK I got whats causing a problem i have two styles first have only fonts and second have style of website, when combine_css is on its sometimes put fonts into combined style, and ALL STYLES from second file are just GONE.

I disabled combine_css and its working fine.

Fonts file look like this:

``` css
@font-face {
  font-family: 'PT Sans';
  font-style: normal;
  font-weight: 400;
  src: local('PT Sans'), local('PTSans-Regular'), url(fonts/pt_sans.woff) format('woff');
}
@font-face {
  font-family: 'PT Sans';
  font-style: normal;
  font-weight: 700;
  src: local('PT Sans Bold'), local('PTSans-Bold'), url(fonts/pt_sans_bold.woff) format('woff');
}
```

EDIT: Well i dont get it, its totally random, i can send my css files if you want maybe you will find something cuz i dont really have no idea whats going on.
